//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreDRXLibrary.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreDRXLibrary.Tests.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;drx id=&quot;101&quot; fileRevision=&quot;1&quot; series=&quot;100&quot; encryptionEnabled=&quot;false&quot; vividity=&quot;0&quot; remembrance=&quot;0&quot; emotion=&quot;0&quot; length=&quot;0&quot; xmlns=&quot;core://drx.schema.core/schemas/DRXSchema.xsd&quot;&gt;&lt;header xmlns=&quot;core://drx.schema.core/schemas/DRXSchema.xsd&quot;&gt;&lt;friendlyName xmlns=&quot;core://drx.schema.core/schemas/DRXSchema.xsd&quot;&gt;Test&lt;/friendlyName&gt;
        ///&lt;secLevel xmlns=&quot;core://drx.schema.core/schemas/DRXSchema.xsd&quot;&gt;PLC&lt;/secLevel&gt;
        ///&lt;redactions xmlns=&quot;core://drx.schema.core/schemas/DRXSchema.xsd&quot;&gt;false&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string syntax_testfile {
            get {
                return ResourceManager.GetString("syntax_testfile", resourceCulture);
            }
        }
    }
}
